name: Linters - TLint

on:
  push:
    branches:
      - feature/*
      - hotfix/*
  workflow_call:
    secrets:
      COMPOSER_AUTH_JSON:
        required: true

jobs:
  tlint:
    name: TLint
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}
    env:
      APP_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'develop' }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0.8
          extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts --ignore-platform-reqs

      - name: Tlint Lint
        run: vendor/bin/duster tlint

      - name: Remove auth.json file
        run: rm -f $GITHUB_WORKSPACE/auth.json
